### ISSUE TITLE
Build error pce/main_pce.o

### ISSUE THREAD

**Issue by cyrilastro** [olderzeus/game-and-watch-retro-go#23]
Hi,
I'm running into build issue since I updated today git repo.
I'm running retro-go under game&watch Mario with 64Mb EXTFLASH and I'm flashing with RPI3B aarch64.

Output of  `git describe --all --long --dirty=-dirty; cd retro-go-stm32; git describe --all --long --dirty=-dirty`
heads/NewUI-0-g002a09a
heads/main-21-g337980a

**Describe the bug**
I'm facing this build output error while compiling

```
[ CC pce ] pce.c
[ CC pce ] sound_pce.c
[ CC pce ] main_pce.c
[ CC gw ] sm500op.c
[ CC gw ] sm510op.c
[ CC gw ] sm500core.c
Core/Src/porting/pce/main_pce.c: In function 'app_main_pce':
Core/Src/porting/pce/main_pce.c:544:13: error: too few arguments to function 'h6280_run'
  544 |             h6280_run();
      |             ^~~~~~~~~
In file included from retro-go-stm32/pce-go/components/pce-go/pce.h:200,
                 from Core/Src/porting/pce/main_pce.c:10:
retro-go-stm32/pce-go/components/pce-go/h6280.h:6:6: note: declared here
    6 | void h6280_run(int32_t cycles);
      |      ^~~~~~~~~
make[1]: *** [Makefile.common:546: build/pce/main_pce.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/admj/opt/game-and-watch-retro-go'
make: *** [Makefile.common:636: flash] Error 2
```

**To Reproduce**
CMD used to flash 
`make -j8 EXTFLASH_SIZE_MB=60 EXTFLASH_OFFSET=4194304 COVERFLOW=1 JPG_QUALITY=90 INTFLASH_BANK=2 flash`

**Desktop environment:**
- Host device OS: RPI3B aarch64 Debian Bullseye 11
- Debugger: RPI

Many thanks for your help !

**Comment by olderzeus** [comment]
It's fixed, Sorry for I forgot merge the main code.

**Comment by cyrilastro** [comment]
Awesome ! I will make a new try later but thanks a lot for your great support !!! 👍👍👍
