### ISSUE TITLE
More than 16 game genie codes breaks the menu

### ISSUE THREAD

**Issue by martaaay** [olderzeus/game-and-watch-retro-go#29]
Hi! I wrote the game genie code. Thanks for pulling it in! 

**Describe the bug**
On the G&W Discord, paletochen noticed some GG menus were empty. After some debugging, we found its because when there's more than 16 codes (actually, not sure what the exact number is), the menu renders as empty. I found this bug too when I wrote the code for the non-coverflow version. I believe when my game genie patch was brought over, the allowable codes was set from 16 to 32 in the parse_roms.py file. The coolest solution would to make the menus more robust, but that's likely a lot more work than just truncating at 16 :). 

**To Reproduce**
Have more than 16 game genie codes for one game (not sure exact number, but the bug was showing when there was 22 codes).

**Expected behavior**
GG codes should show in the menu. In this case, the menu was empty.

**Screenshots**
![ggcodebug](https://user-images.githubusercontent.com/1003320/168667026-189cb5e5-f968-4cb2-919b-7110ae084706.png)

**Comment by olderzeus** [comment]
Set the MAX_GAME_GENIE_CODES 16 to fixed.
when I extent menu to show more items, It's will set to 32.
