### ISSUE TITLE
Broken compile with CHEAT_CODES=1 and no msx games

### ISSUE THREAD

**Issue by RetroLink7** [olderzeus/game-and-watch-retro-go#34]
**Describe the bug**
Compile is broken when CHEAT_CODES=1 is enabled and there are no msx ROMs detected:

game-and-watch-retro-go/Core/Src/porting/odroid_overlay.c:1083: undefined reference to `update_cheats_msx'

**To Reproduce**
At current head (d8c35d0):
1. Add a NES ROM and corresponding ggcodes file, but don't include any MSX ROMs.
2. Compile with: make CHEAT_CODES=1 flash

**Expected behavior**
Should compile without errors.

**Desktop environment:**
- Host device OS: RPI4

**Additional context**
The broken reference to update_cheats_msx() is likely due to the build optimization where compilation for systems without ROMs present is skipped.

In this case, if there are no MSX ROMs, update_cheats_msx() won't be available in Core/Src/porting/odroid_overlay.c.  update_cheats_msx() is defined in Core/Src/porting/msx/main_msx.c.

**Comment by olderzeus** [comment]
Thanks
