### ISSUE TITLE
刷机以后，存档能导入导出吗？

### ISSUE THREAD

**Issue by duoffice** [olderzeus/game-and-watch-retro-go#42]
请问一下，这样刷机以后，存档还能导入导出吗？比如说下一次我进行二次刷机后，是不是第一次刷机打的存档都没了？谢谢！

**Comment by olderzeus** [comment]
存档是可以导出，但需要机器上刷机版本的elf那些个文件。
由于使用了中文名称，导出的文件名和导入的识别会出现异常，需要你自行查阅相关脚本进行调整。
scripts/saves_restore.sh 和 saves_backup.sh 文件脚本.
