### ISSUE TITLE
Can 64M FLASH be filled?

### ISSUE THREAD

**Issue by duoffice** [olderzeus/game-and-watch-retro-go#44]
I replaced the 64M Flash and made a dual system. Now there are 60M available. May I ask if I can fill up the 60M when I install the game? Or do you need to reserve some space? thank you

**Comment by olderzeus** [comment]
you can use ·make size· to see overview of the space

**Comment by duoffice** [comment]
Yes, what I mean is that if I use make size, the generated compiled file is 59M with only 1M free space left, will it affect the system? Like: Crash? Running out of archive space? Other puzzling questions? thank you

**Comment by olderzeus** [comment]
if you compiled more file that space override the chip allow, make will be abort.
otherwise don't worry.
