### ISSUE TITLE
lcd游戏转换不了

### ISSUE THREAD

**Issue by hexiaotun** [olderzeus/game-and-watch-retro-go#46]
有人知道怎么转换游戏最新的命令吗，总是显示出错，跪求转好的gw游戏

**Comment by olderzeus** [comment]
See:https://gist.github.com/DNA64/16fed499d6bd4664b78b4c0a9638e4ef

**Comment by hexiaotun** [comment]
就是按这个教程，里面搞到最后一步就报错了，说python3.8缺东西
